declarr:
  formatDbBranch: stable
  formatDbRepo: 'https://github.com/Dictionarry-Hub/Database'
  globalResolvePaths:
    - $.*.config.host.password
    - $.*.config.host.passwordConfirmation
    - $.*.config.host.apiKey
    - $.*.applications.*.fields.apiKey
    - $.*.indexer.*.fields.password
    - $.*.downloadClient.*.fields.password
  stateDir: /var/lib/declarr
prowlarr:
  appProfile:
    Automatic:
      enableAutomaticSearch: true
      enableInteractiveSearch: false
      enableRss: true
      minimumSeeders: 1
    Interactive Search:
      enableAutomaticSearch: false
      enableInteractiveSearch: true
      enableRss: false
      minimumSeeders: 1
    Standard:
      enableAutomaticSearch: true
      enableInteractiveSearch: true
      enableRss: true
      minimumSeeders: 1
  applications:
    Radarr:
      fields:
        apiKey: /run/secrets/radarr/api-key_declarr
      implementation: Radarr
      syncLevel: fullSync
    Sonarr:
      fields:
        apiKey: /run/secrets/sonarr/api-key_declarr
      implementation: Sonarr
      syncLevel: fullSync
  config:
    host:
      analyticsEnabled: false
      apiKey: /run/secrets/prowlarr/api-key_declarr
      authenticationMethod: forms
      authenticationRequired: enabled
      backupInterval: 7
      backupRetention: 28
      bindAddress: '*'
      branch: main
      consoleLogLevel: ''
      instanceName: Prowlarr
      logLevel: debug
      logSizeLimit: 1
      password: /run/secrets/prowlarr/password_declarr
      passwordConfirmation: /run/secrets/prowlarr/password_declarr
      port: 9696
      proxyEnabled: false
      sslCertPassword: ''
      sslCertPath: ''
      updateScriptPath: ''
      urlBase: ''
      username: admin
    ui:
      firstDayOfWeek: 1
      theme: dark
      timeFormat: 'HH:mm'
  declarr:
    type: prowlarr
    url: 'http://localhost:9696'
  downloadClient:
    qBittorrent:
      fields:
        host: 192.168.15.1
        password: /run/secrets/qbit/password_declarr
        port: 8080
        sequentialOrder: true
        username: admin
      implementation: QBittorrent
  indexer:
    1337x:
      appProfileId: Standard
      fields:
        definitionFile: 1337x
        downloadlink: 1
        downloadlink2: 0
        sort: 2
        type: 1
      implementation: Cardigann
      priority: 25
      tags:
        - FlareSolverr
    LimeTorrents:
      fields:
        definitionFile: limetorrents
        downloadlink: 1
        downloadlink2: 0
      implementation: Cardigann
      priority: 30
    The Pirate Bay:
      fields:
        definitionFile: thepiratebay
      implementation: Cardigann
      priority: 30
    TorrentLeech:
      appProfileId: Interactive Search
      fields:
        definitionFile: torrentleech
        freeleech: false
        password: /run/secrets/prowlarr/indexers/torrentLeech/password_declarr
        username: upidapi
      implementation: Cardigann
      priority: 25
      tags:
        - FlareSolverr
    TorrentLeech freeleech:
      appProfileId: Automatic
      fields:
        definitionFile: torrentleech
        freeleech: true
        password: /run/secrets/prowlarr/indexers/torrentLeech/password_declarr
        username: upidapi
      implementation: Cardigann
      priority: 20
      tags:
        - FlareSolverr
    YTS:
      fields:
        definitionFile: yts
      implementation: Cardigann
      priority: 30
  indexerProxy:
    FlareSolverr:
      fields:
        host: 'http://localhost:8191/'
        requestTimeout: 60
      tags:
        - FlareSolverr
radarr:
  config:
    host:
      analyticsEnabled: false
      apiKey: /run/secrets/radarr/api-key_declarr
      authenticationMethod: forms
      authenticationRequired: enabled
      backupInterval: 7
      backupRetention: 28
      bindAddress: '*'
      branch: main
      consoleLogLevel: ''
      instanceName: Radarr
      logLevel: debug
      logSizeLimit: 1
      password: /run/secrets/radarr/password_declarr
      passwordConfirmation: /run/secrets/radarr/password_declarr
      port: 7878
      proxyEnabled: false
      sslCertPassword: ''
      sslCertPath: ''
      updateScriptPath: ''
      urlBase: ''
      username: admin
    mediamanagement:
      autoUnmonitorPreviouslyDownloadedEpisodes: false
      chmodFolder: '755'
      chownGroup: ''
      copyUsingHardlinks: true
      createEmptySeriesFolders: true
      deleteEmptyFolders: false
      downloadPropersAndRepacks: preferAndUpgrade
      enableMediaInfo: true
      episodeTitleRequired: always
      extraFileExtensions: srt
      fileDate: none
      importExtraFiles: false
      minimumFreeSpaceWhenImporting: 100
      recycleBin: ''
      recycleBinCleanupDays: 7
      rescanAfterRefresh: always
      scriptImportPath: ''
      setPermissionsLinux: false
      skipFreeSpaceCheckWhenImporting: false
      useScriptImport: false
    naming:
      movieFolderFormat: '{Movie Title} ({Release Year})'
      renameMovies: true
      replaceIllegalCharacters: true
      standardMovieFormat: '{Movie Title} ({Release Year}) {Quality Title} {MediaInfo VideoCodec}'
    ui:
      firstDayOfWeek: 1
      theme: dark
      timeFormat: 'HH:mm'
  customFormat: {}
  declarr:
    type: radarr
    url: 'http://localhost:7878'
  downloadClient:
    qBittorrent:
      fields:
        host: 192.168.15.1
        password: /run/secrets/qbit/password_declarr
        port: 8080
        sequentialOrder: true
        username: admin
      implementation: QBittorrent
  qualityDefinition:
    Bluray-1080p:
      maxSize: 2000
      minSize: 50.8
      preferredSize: 1999
    Bluray-2160p:
      maxSize: 2000
      minSize: 102
      preferredSize: 1999
    Bluray-720p:
      maxSize: 2000
      minSize: 25.7
      preferredSize: 1999
    HDTV-1080p:
      maxSize: 2000
      minSize: 33.8
      preferredSize: 1999
    HDTV-2160p:
      maxSize: 2000
      minSize: 85
      preferredSize: 1999
    HDTV-720p:
      maxSize: 2000
      minSize: 17.1
      preferredSize: 1999
    Remux-1080p:
      maxSize: 2000
      minSize: 102
      preferredSize: 1999
    Remux-2160p:
      maxSize: 2000
      minSize: 187.4
      preferredSize: 1999
    WEBDL-1080p:
      maxSize: 2000
      minSize: 12.5
      preferredSize: 1999
    WEBDL-2160p:
      maxSize: 2000
      minSize: 34.5
      preferredSize: 1999
    WEBDL-720p:
      maxSize: 2000
      minSize: 12.5
      preferredSize: 1999
    WEBRip-1080p:
      maxSize: 2000
      minSize: 12.5
      preferredSize: 1999
    WEBRip-2160p:
      maxSize: 2000
      minSize: 34.5
      preferredSize: 1999
    WEBRip-720p:
      maxSize: 2000
      minSize: 12.5
      preferredSize: 1999
  qualityProfile:
    1080p Balanced: {}
    1080p Quality: {}
    2160p Balanced: {}
    2160p Quality: {}
  rootFolder:
    - /raid/media/movies
sonarr:
  config:
    host:
      analyticsEnabled: false
      apiKey: /run/secrets/sonarr/api-key_declarr
      authenticationMethod: forms
      authenticationRequired: enabled
      backupInterval: 7
      backupRetention: 28
      bindAddress: '*'
      branch: main
      consoleLogLevel: ''
      instanceName: Sonarr
      logLevel: debug
      logSizeLimit: 1
      password: /run/secrets/sonarr/password_declarr
      passwordConfirmation: /run/secrets/sonarr/password_declarr
      port: 8989
      proxyEnabled: false
      sslCertPassword: ''
      sslCertPath: ''
      updateScriptPath: ''
      urlBase: ''
      username: admin
    mediamanagement:
      autoUnmonitorPreviouslyDownloadedEpisodes: false
      chmodFolder: '755'
      chownGroup: ''
      copyUsingHardlinks: true
      createEmptySeriesFolders: true
      deleteEmptyFolders: false
      downloadPropersAndRepacks: preferAndUpgrade
      enableMediaInfo: true
      episodeTitleRequired: always
      extraFileExtensions: srt
      fileDate: none
      importExtraFiles: false
      minimumFreeSpaceWhenImporting: 100
      recycleBin: ''
      recycleBinCleanupDays: 7
      rescanAfterRefresh: always
      scriptImportPath: ''
      setPermissionsLinux: false
      skipFreeSpaceCheckWhenImporting: false
      useScriptImport: false
    naming:
      animeEpisodeFormat: >-
        s{season:00}e{episode:00} - {Episode Title} {Quality Title} {MediaInfo
        VideoCodec}
      colonReplacementFormat: 4
      customColonReplacementFormat: ''
      dailyEpisodeFormat: '{Air-Date} - {Episode Title} {Quality Title} {MediaInfo VideoCodec}'
      multiEpisodeStyle: 5
      renameEpisodes: true
      replaceIllegalCharacters: true
      seasonFolderFormat: 'Season {season}'
      seriesFolderFormat: '{Series Title}'
      specialsFolderFormat: Specials
      standardEpisodeFormat: >-
        s{season:00}e{episode:00} - {Episode Title} {Quality Title} {MediaInfo
        VideoCodec}
    ui:
      firstDayOfWeek: 1
      theme: dark
      timeFormat: 'HH:mm'
  customFormat: {}
  declarr:
    type: sonarr
    url: 'http://localhost:8989'
  downloadClient:
    qBittorrent:
      fields:
        host: 192.168.15.1
        password: /run/secrets/qbit/password_declarr
        port: 8080
        sequentialOrder: true
        username: admin
      implementation: QBittorrent
  qualityDefinition:
    Bluray-1080p:
      maxSize: 1000
      minSize: 50.4
      preferredSize: 995
    Bluray-1080p Remux:
      maxSize: 1000
      minSize: 69.1
      preferredSize: 995
    Bluray-2160p:
      maxSize: 1000
      minSize: 94.6
      preferredSize: 995
    Bluray-2160p Remux:
      maxSize: 1000
      minSize: 187.4
      preferredSize: 995
    Bluray-720p:
      maxSize: 1000
      minSize: 17.1
      preferredSize: 995
    HDTV-1080p:
      maxSize: 1000
      minSize: 15
      preferredSize: 995
    HDTV-2160p:
      maxSize: 1000
      minSize: 25
      preferredSize: 995
    HDTV-720p:
      maxSize: 1000
      minSize: 10
      preferredSize: 995
    WEBDL-1080p:
      maxSize: 1000
      minSize: 15
      preferredSize: 995
    WEBDL-2160p:
      maxSize: 1000
      minSize: 25
      preferredSize: 995
    WEBDL-720p:
      maxSize: 1000
      minSize: 10
      preferredSize: 995
    WEBRip-1080p:
      maxSize: 1000
      minSize: 15
      preferredSize: 995
    WEBRip-2160p:
      maxSize: 1000
      minSize: 25
      preferredSize: 995
    WEBRip-720p:
      maxSize: 1000
      minSize: 10
      preferredSize: 995
  qualityProfile:
    1080p Balanced: {}
    1080p Quality: {}
    2160p Balanced: {}
    2160p Quality: {}
  rootFolder:
    - /raid/media/tv
